apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_DATABASE_CONFIG: "a3ViZW5ld3M="
  DB_USERNAME_CONFIG: "a3ViZW5ld3M="
  DB_PASSWORD_CONFIG: "UGcjMTIz"
  DB_HOST_CONFIG: "cG9zdGdyZXNxbA=="